site_name: Learn with VGWB
site_url: https://learn.vgwb.org
site_author: VGWB
site_description: 

copyright: Open Source website by VGWB

theme:
  name: material
  language: en
  logo: assets/ieedo_logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  features:
    - navigation.tabs
    - navigation.top
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition

# Plugins
#plugins:
#  - minify:
#      minify_html: true

repo_url: https://github.com/vgwb/guide_DGBL/
edit_uri: edit/main/docs/

extra_css:
  - stylesheets/extra.css

# extra:
#   alternate:
#     - name: English
#       lang: en
#     - name: Italian
#       lang: it