site_name: IEEDO - DGBL
site_url: https://learn.vgwb.org
site_author: VGWB
site_description: 

copyright: Open Source website by <a href="https://vgwb.org>VGWB.org</a>

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  features:
    - navigation.footer
    - navigation.indexes
#    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.top
#    - navigation.sections
    - announce.dismiss
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - tables
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - i18n:
      default_language: en
      docs_structure: suffix
      languages:
        en:
          name: English
        es:
          name: Espanol
        de:
          name: German
        gr:
          name: Greek
        se:
          name: Swedish
      material_alternate: true

#repo_url: https://github.com/vgwb/learn.vgwb.org/
#edit_uri: edit/main/docs/

extra_css:
  - assets/stylesheets/extra.css

# extra:
#   alternate:
#     - name: English
#       lang: en
#     - name: Italian
#       lang: it